name: connect via ssh

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        python3 write_key.py
        chmod og-rwx id_ssh
        ssh -vv -i id_ssh gh_euroscipy@euroscipy.g-node.org ls

